# Generated by Django 5.2.7 on 2025-10-02 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField()),
                ('methodologies', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=150)),
                ('performance', models.CharField(max_length=150)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=150)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('parent', models.CharField(blank=True, max_length=150, null=True)),
                ('course', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('birth_place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorAEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aees', to='schedule.professor')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(related_name='sessions', through='schedule.SessionAttendance', to='schedule.student'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('generated_date', models.DateField()),
                ('summary', models.TextField()),
                ('notes', models.TextField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schedule.professoraee')),
                ('reviews', models.ManyToManyField(related_name='reports', to='schedule.review')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schedule.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.user'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.user'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recommendations', models.TextField()),
                ('activities', models.TextField()),
                ('resources', models.TextField()),
                ('pedagogical_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='schedule.pedagogicalproposal')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='schedule.professoraee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='schedule.student')),
            ],
            options={
                'unique_together': {('date', 'student')},
            },
        ),
    ]
