# Generated by Django 5.2.7 on 2025-10-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
