# Generated by Django 5.2.7 on 2025-12-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_professor_user_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pedagogical_proposal',
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='plan',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='student',
        ),
        migrations.RemoveField(
            model_name='report',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student',
        ),
        migrations.DeleteModel(
            name='PedagogicalProposal',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
