# Generated by Django 5.2.7 on 2025-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_session_time_alter_session_date_alter_session_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
